apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
<<<<<<< HEAD
  replicas: 1
=======
  replicas: 3
>>>>>>> 5810510183ffafdc6b5ad56544e6d64ab43ab839
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result
        name: result
        ports:
        - containerPort: 80
          name: result
