apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
<<<<<<< HEAD
    nodePort: 31002
=======
    nodePort: 31002
>>>>>>> 5810510183ffafdc6b5ad56544e6d64ab43ab839
  selector:
    app: vote
  
