apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
<<<<<<< HEAD
  replicas: 1
=======
  replicas: 3
>>>>>>> 5810510183ffafdc6b5ad56544e6d64ab43ab839
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: vote
        ports:
        - containerPort: 80
          name: vote
